<!-- wp:paragraph --><p><strong>An electricity bill can charge a business for two different things: how much energy it used and how much power it demanded at its busiest moment. That second number is the idea behind a demand charge.</strong></p><!-- /wp:paragraph -->
<!-- wp:paragraph --><p>For homes, electricity bills are usually dominated by kilowatt-hours. Large commercial and industrial customers may also pay based on their highest measured kilowatt demand during a billing period. That makes a short power spike potentially expensive even when total monthly energy use barely changes.</p><!-- /wp:paragraph -->
<!-- wp:heading --><h2 class="wp-block-heading">kW And kWh Measure Different Things</h2><!-- /wp:heading -->
<!-- wp:paragraph --><p>A kilowatt measures power: the rate at which electricity is being used right now. A kilowatt-hour measures energy: one kilowatt used continuously for one hour.</p><!-- /wp:paragraph -->
<!-- wp:paragraph --><p>A 1 MW load running for one hour consumes 1 MWh. If the same site briefly jumps to 2 MW, its energy consumption may not rise very much, but its measured peak demand can double during that interval.</p><!-- /wp:paragraph -->
<!-- wp:heading --><h2 class="wp-block-heading">What A Demand Charge Pays For</h2><!-- /wp:heading -->
<!-- wp:paragraph --><p>The grid has to be capable of serving a customer when that customer reaches peak load, not merely when it is operating at its monthly average. Utilities therefore use demand-based rates to recover some of the cost of generation, substations, transformers, feeders and other infrastructure sized around peak requirements.</p><!-- /wp:paragraph -->
<!-- wp:paragraph --><p>This is different from <a href="https://bitcoinversus.tech/2026/10/06/energy-what-is-power-factor-kw-kva-kvar/">power factor</a>, which describes the relationship among real, reactive and apparent power. A site can have excellent power factor and still create a large demand peak.</p><!-- /wp:paragraph -->
<!-- wp:heading --><h2 class="wp-block-heading">How The Peak Is Measured</h2><!-- /wp:heading -->
<!-- wp:paragraph --><p>Utilities do not necessarily bill from a one-second spike. Commercial tariffs commonly calculate demand over a defined interval, such as a rolling or fixed 15-minute period, although the exact interval and formula depend on the utility and rate schedule.</p><!-- /wp:paragraph -->
<!-- wp:paragraph --><p>Imagine a facility averaging 800 kW for most of the month but reaching 1,200 kW during a billing interval when cooling equipment, pumps and compute loads overlap. The energy portion of the bill reflects accumulated kWh, while the demand portion may be based on that 1,200 kW peak.</p><!-- /wp:paragraph -->
<!-- wp:heading --><h2 class="wp-block-heading">Why Data Centers Care About Peaks</h2><!-- /wp:heading -->
<!-- wp:paragraph --><p>Data centers combine dense IT equipment with cooling, pumps, fans and electrical conversion equipment. A large synchronized load change can therefore affect both the facility’s utility bill and the amount of electrical capacity it must reserve.</p><!-- /wp:paragraph -->
<!-- wp:paragraph --><p>That is one reason some operators add <a href="https://bitcoinversus.tech/2026/10/05/energy-behind-the-meter-power-explained-data-centers-onsite-generation/">behind-the-meter generation and storage</a>. Batteries or on-site generation can sometimes reduce grid draw during expensive peaks, depending on the tariff and operating design.</p><!-- /wp:paragraph -->
<!-- wp:heading --><h2 class="wp-block-heading">Bitcoin Mining Has An Unusual Advantage</h2><!-- /wp:heading -->
<!-- wp:paragraph --><p>Many computing workloads cannot simply disappear when electricity becomes expensive. Bitcoin miners can often reduce consumption quickly by curtailing machines, making the load more flexible than a conventional always-on industrial process.</p><!-- /wp:paragraph -->
<!-- wp:paragraph --><p>Our guide to <a href="https://bitcoinversus.tech/2026/10/06/can-bitcoin-mining-stabilize-the-power-grid-or-nah/">Bitcoin mining as a flexible grid load</a> explains why the ability to turn megawatts down quickly can have value during periods when the electrical system is stressed.</p><!-- /wp:paragraph -->
<!-- wp:heading --><h2 class="wp-block-heading">Demand Charges Can Change Operating Decisions</h2><!-- /wp:heading -->
<!-- wp:paragraph --><p>If a tariff contains a substantial demand component, operators may schedule large loads at different times, stagger equipment startup, use batteries for peak shaving or automate controls to keep the site below a target threshold.</p><!-- /wp:paragraph -->
<!-- wp:paragraph --><p>The exact economics depend entirely on the tariff. Some rates use seasonal peaks, time-of-use windows or ratchets that carry part of an earlier peak into later billing periods. Operators therefore need the actual utility rate sheet rather than a generic cents-per-kWh assumption.</p><!-- /wp:paragraph -->
<!-- wp:heading --><h2 class="wp-block-heading">The Easy Mental Model</h2><!-- /wp:heading -->
<!-- wp:paragraph --><p>Think of energy charges as paying for how much water flowed through a pipe during the month. A demand charge is closer to paying for how wide the pipe had to be to handle your biggest rush. One measures total consumption; the other reflects the peak capacity the system had to be ready to supply.</p><!-- /wp:paragraph -->
<!-- wp:heading --><h2 class="wp-block-heading">Sources</h2><!-- /wp:heading -->
<!-- wp:paragraph --><p>Technical references: <a href="https://www.eia.gov/energyexplained/electricity/prices-and-factors-affecting-prices.php">U.S. Energy Information Administration: Electricity Prices</a> and <a href="https://www.energy.gov/femp/demand-response-and-time-variable-pricing-programs">U.S. Department of Energy: Demand Response and Time-Variable Pricing</a>.</p><!-- /wp:paragraph -->
<!-- wp:heading --><h2 class="wp-block-heading">BitcoinVersus.Tech</h2><!-- /wp:heading -->
<!-- wp:heading {"level":3} --><h3 class="wp-block-heading">Advertisement</h3><!-- /wp:heading -->
<!-- wp:embed {"url":"https://twitter.com/1BitcoinVersus/status/1937006164555993338","type":"rich","providerNameSlug":"x","responsive":true} --><figure class="wp-block-embed is-type-rich is-provider-x wp-block-embed-x"><div class="wp-block-embed__wrapper">https://twitter.com/1BitcoinVersus/status/1937006164555993338</div><figcaption class="wp-element-caption"><em>BitcoinVersus.Tech advertisement.</em></figcaption></figure><!-- /wp:embed -->
<!-- wp:heading {"level":3} --><h3 class="wp-block-heading">Editor’s Note</h3><!-- /wp:heading -->
<!-- wp:paragraph --><p><strong><em>We volunteer daily to help keep the information on this platform verifiably accurate. If you would like to support our independent research, please donate here: 3C9o19EH5HSiwEPyCTmEKzxhNCbo2X6TTb</em></strong></p><!-- /wp:paragraph -->
<!-- wp:paragraph --><p>BitcoinVersus.tech is not a financial advisor. Content is provided for informational purposes.</p><!-- /wp:paragraph -->