<!-- wp:heading --><h2 class="wp-block-heading">Elementary Overview</h2><!-- /wp:heading -->
<!-- wp:paragraph --><p>In <a href="https://bitcoinversus.tech/2026/09/10/windows-server-guide-for-it-technicians-and-administrators/"><strong>Windows</strong></a>, many important programs run in the background as <strong>services</strong>. The built-in <code>sc.exe</code> utility talks to the <strong>Service Control Manager (SCM)</strong>, while <code>sc query</code> asks the SCM for the current state of a service or driver. This makes it a natural follow-up to <a href="https://bitcoinversus.tech/2026/10/06/windows-command-33-net-start/"><strong>Windows Command #33 — <code>net start</code></strong></a>: <code>net start</code> can start or list running services, while <code>sc query</code> exposes more diagnostic state information. Microsoft documents <code>sc.exe query</code> for current Windows client and server releases, including <a href="https://bitcoinversus.tech/2026/10/03/windows-11-26h2-one-restart-enablement-package/"><strong>Windows 11</strong></a>. The simplest mental model is: <code>net start</code> asks “what is running or can I start it?”; <code>sc query</code> asks “what state is this service actually in?”</p><!-- /wp:paragraph -->
<!-- wp:embed {"url":"https://www.youtube.com/watch?v=Y9ZVXCVw4Yw","type":"video","providerNameSlug":"youtube","responsive":true} --><figure class="wp-block-embed is-type-video is-provider-youtube wp-block-embed-youtube"><div class="wp-block-embed__wrapper">
https://www.youtube.com/watch?v=Y9ZVXCVw4Yw
</div><figcaption class="wp-element-caption"><em>Windows service-management demonstration using the sc command-line utility.</em></figcaption></figure><!-- /wp:embed -->

<!-- wp:heading --><h2 class="wp-block-heading">Query One Service and Read Its State</h2><!-- /wp:heading -->
<!-- wp:paragraph --><p>Start with a specific service name: <code>sc.exe query wuauserv</code> asks Windows for the status of the Windows Update service. The output includes <code>SERVICE_NAME</code>, service <code>TYPE</code>, <code>STATE</code>, Windows and service exit codes, <code>CHECKPOINT</code>, and <code>WAIT_HINT</code>. A state such as <code>4 RUNNING</code> means the service is running; <code>1 STOPPED</code> means it is stopped. <code>CHECKPOINT</code> and <code>WAIT_HINT</code> become especially useful when a service is transitioning and troubleshooting whether it is making progress. Before changing anything, query first—just as a technician should inspect <a href="https://bitcoinversus.tech/2026/10/06/easy-tech-read-what-is-a-device-driver-how-hardware-talks-to-the-operating-system/"><strong>device drivers</strong></a>, processes, and system state before applying a fix.</p><!-- /wp:paragraph -->
<!-- wp:embed {"url":"https://www.youtube.com/watch?v=0EvpF3Xpnqo","type":"video","providerNameSlug":"youtube","responsive":true} --><figure class="wp-block-embed is-type-video is-provider-youtube wp-block-embed-youtube"><div class="wp-block-embed__wrapper">
https://www.youtube.com/watch?v=0EvpF3Xpnqo
</div><figcaption class="wp-element-caption"><em>Command Prompt demonstration of Windows service creation, configuration, starting, and verification.</em></figcaption></figure><!-- /wp:embed -->

<!-- wp:heading --><h2 class="wp-block-heading">Enumerate Running, Stopped, and Driver Services</h2><!-- /wp:heading -->
<!-- wp:paragraph --><p>Running <code>sc.exe query</code> with no service name enumerates active services by default. Use <code>sc.exe query state= all</code> to include stopped services, and <code>sc.exe query type= driver</code> to enumerate <a href="https://bitcoinversus.tech/2026/10/06/easy-tech-read-what-is-a-device-driver-how-hardware-talks-to-the-operating-system/"><strong>drivers</strong></a>. Microsoft’s syntax is unusual but important: options such as <code>state=</code> and <code>type=</code> include the equals sign in the option name and require a space before the value. You can also query a remote <a href="https://bitcoinversus.tech/2026/09/10/windows-server-guide-for-it-technicians-and-administrators/"><strong>Windows Server</strong></a> with UNC-style syntax such as <code>sc.exe \\SERVER01 query</code>, assuming the account, firewall, RPC, and remote-service permissions allow it. That connects service inspection directly to broader <a href="https://bitcoinversus.tech/2026/10/06/ositc-001-it-systems-fundamentals-hardware-operating-systems-networks-troubleshooting/"><strong>IT troubleshooting</strong></a> and <a href="https://bitcoinversus.tech/2026/10/06/osntc-017-copper-ethernet-cabling-rj45-t568b-cat5e-cat6-cat6a-100m-poe-cable-testing/"><strong>networking</strong></a> practice.</p><!-- /wp:paragraph -->
<!-- wp:embed {"url":"https://www.youtube.com/watch?v=k2diP0g1Z0A","type":"video","providerNameSlug":"youtube","responsive":true} --><figure class="wp-block-embed is-type-video is-provider-youtube wp-block-embed-youtube"><div class="wp-block-embed__wrapper">
https://www.youtube.com/watch?v=k2diP0g1Z0A
</div><figcaption class="wp-element-caption"><em>Windows Services demonstration showing service discovery and management through the Services console.</em></figcaption></figure><!-- /wp:embed -->

<!-- wp:heading --><h2 class="wp-block-heading">Use sc query as the Read-Only Step Before Service Changes</h2><!-- /wp:heading -->
<!-- wp:paragraph --><p><code>sc query</code> is primarily an inspection command; other <code>sc.exe</code> operations can start, stop, configure, create, or delete services. That distinction matters because service changes can disable networking, updates, security agents, storage functions, or application dependencies. A disciplined workflow is <strong>identify → query → interpret → change only if justified → query again</strong>. The same service state can also be inspected through the graphical <strong>Services</strong> console or <a href="https://bitcoinversus.tech/2026/09/10/windows-server-guide-for-it-technicians-and-administrators/"><strong>PowerShell</strong></a> commands such as <code>Get-Service</code>, but <code>sc query</code> remains useful in scripts, recovery sessions, remote administration, and minimal command-line environments. Microsoft’s Service Control Manager is the underlying Windows component maintaining installed-service records and status information.</p><!-- /wp:paragraph -->
<!-- wp:embed {"url":"https://www.youtube.com/watch?v=pb8trpQkCPs","type":"video","providerNameSlug":"youtube","responsive":true} --><figure class="wp-block-embed is-type-video is-provider-youtube wp-block-embed-youtube"><div class="wp-block-embed__wrapper">
https://www.youtube.com/watch?v=pb8trpQkCPs
</div><figcaption class="wp-element-caption"><em>Practical Windows Services troubleshooting demonstration showing service status, startup, stopping, and restarting.</em></figcaption></figure><!-- /wp:embed -->

<!-- wp:heading --><h2 class="wp-block-heading">Practical Command Set</h2><!-- /wp:heading -->
<!-- wp:list --><ul class="wp-block-list"><li><code>sc.exe query</code> — list active services.</li><li><code>sc.exe query wuauserv</code> — inspect the Windows Update service.</li><li><code>sc.exe query state= all</code> — list active and inactive services.</li><li><code>sc.exe query type= driver</code> — enumerate drivers.</li><li><code>sc.exe query type= all</code> — query services and drivers.</li><li><code>sc.exe \\SERVER01 query</code> — query services on a permitted remote Windows computer.</li><li><code>sc.exe queryex wuauserv</code> — request extended service information, including process information when available.</li></ul><!-- /wp:list -->

<!-- wp:heading --><h2 class="wp-block-heading">How to Read Common State Values</h2><!-- /wp:heading -->
<!-- wp:list --><ul class="wp-block-list"><li><code>1 STOPPED</code> — the service is not running.</li><li><code>2 START_PENDING</code> — Windows is waiting for the service to finish starting.</li><li><code>3 STOP_PENDING</code> — the service is in the process of stopping.</li><li><code>4 RUNNING</code> — the service is running.</li><li><code>5 CONTINUE_PENDING</code> — a paused service is resuming.</li><li><code>6 PAUSE_PENDING</code> — the service is moving toward a paused state.</li><li><code>7 PAUSED</code> — the service is paused.</li></ul><!-- /wp:list -->

<!-- wp:heading --><h2 class="wp-block-heading">Exercises</h2><!-- /wp:heading -->
<!-- wp:list {"ordered":true} --><ol class="wp-block-list"><li>Open Command Prompt and run <code>sc.exe query</code>. Identify three running services.</li><li>Run <code>sc.exe query state= all</code>. Find one stopped service without changing it.</li><li>Query <code>wuauserv</code> directly and record its <code>STATE</code>, exit code, checkpoint, and wait hint.</li><li>Run <code>sc.exe query type= driver</code> and identify two driver-service names.</li><li>Compare <code>sc.exe query</code> with <code>net start</code> from Windows Command #33. Explain which gives richer diagnostic output.</li><li>On a lab machine, compare the same service in <code>sc.exe query</code>, Services, and <code>Get-Service</code>.</li></ol><!-- /wp:list -->

<!-- wp:heading --><h2 class="wp-block-heading">Knowledge Check + Answers</h2><!-- /wp:heading -->
<!-- wp:list {"ordered":true} --><ol class="wp-block-list"><li><strong>What does <code>sc.exe query</code> communicate with?</strong> The Windows Service Control Manager.</li><li><strong>What does <code>STATE : 4 RUNNING</code> mean?</strong> The service is currently running.</li><li><strong>How do you include stopped services?</strong> Use <code>sc.exe query state= all</code>.</li><li><strong>How do you enumerate drivers?</strong> Use <code>sc.exe query type= driver</code>.</li><li><strong>Why query before changing a service?</strong> It establishes the current state and reduces unnecessary or harmful configuration changes.</li><li><strong>What are <code>CHECKPOINT</code> and <code>WAIT_HINT</code> useful for?</strong> Interpreting progress while a service is in a pending transition.</li></ol><!-- /wp:list -->

<!-- wp:heading --><h2 class="wp-block-heading">Primary Technical References</h2><!-- /wp:heading -->
<!-- wp:list --><ul class="wp-block-list"><li><a href="https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/sc-query">Microsoft Learn — sc.exe query</a></li><li><a href="https://learn.microsoft.com/en-us/windows/win32/services/service-control-manager">Microsoft Learn — Service Control Manager</a></li></ul><!-- /wp:list -->

<!-- wp:heading --><h2 class="wp-block-heading"><strong><em>BitcoinVersus.Tech</em></strong></h2><!-- /wp:heading -->
<!-- wp:paragraph --><p><strong><em>Advertisement</em></strong></p><!-- /wp:paragraph -->
<!-- wp:embed {"url":"https://twitter.com/1BitcoinVersus/status/1937006164555993338","type":"rich","providerNameSlug":"x","responsive":true} --><figure class="wp-block-embed is-type-rich is-provider-x wp-block-embed-x"><div class="wp-block-embed__wrapper">
https://twitter.com/1BitcoinVersus/status/1937006164555993338
</div><figcaption class="wp-element-caption"><em>BitcoinVersus.Tech advertisement.</em></figcaption></figure><!-- /wp:embed -->
<!-- wp:paragraph --><p><strong><em>Editor's Note:</em></strong></p><!-- /wp:paragraph -->
<!-- wp:paragraph --><p><strong><em>We volunteer daily to ensure the credibility of the information on this platform is Verifiably True. If you would like to support our research initiatives, please donate here: 3C9o19EH5HSiwEPyCTmEKzxhNCbo2X6TTb</em></strong></p><!-- /wp:paragraph -->
<!-- wp:paragraph --><p>BitcoinVersus.tech is not a financial advisor. Content is provided for informational purposes.</p><!-- /wp:paragraph -->