<!-- wp:heading --><h2 class="wp-block-heading">Elementary Overview</h2><!-- /wp:heading -->
<!-- wp:paragraph --><p>An <a href="https://bitcoinversus.tech/2025/12/21/robotics-industrial-robot-types/"><strong>industrial robot</strong></a> does not work alone. It must exchange signals with a <strong>PLC</strong>, sensors, conveyors, <a href="https://bitcoinversus.tech/2026/10/06/osrtc-004-end-effectors-tool-center-point-setup-grippers-tcp-calibration-payload-io-safe-verification/"><strong>end effectors</strong></a>, and safety devices so the entire workcell knows when it is safe and ready to move. The simplest signals are <strong>digital inputs</strong> and <strong>digital outputs</strong>: an input tells the robot what is happening outside the controller, while an output tells another device what the robot wants or what state it is in. A good technician learns to follow the entire handshake: command → output → field device → sensor feedback → input → next robot or PLC action.</p><!-- /wp:paragraph -->
<!-- wp:embed {"url":"https://www.youtube.com/watch?v=B65detMhnoc","type":"video","providerNameSlug":"youtube","responsive":true,"className":"wp-embed-aspect-16-9 wp-has-aspect-ratio"} --><figure class="wp-block-embed is-type-video is-provider-youtube wp-block-embed-youtube wp-embed-aspect-16-9 wp-has-aspect-ratio"><div class="wp-block-embed__wrapper">
https://www.youtube.com/watch?v=B65detMhnoc
</div><figcaption class="wp-element-caption"><em>RealPars — Sinking and Sourcing PLC Inputs Explained | What is the Difference? Electrical compatibility of discrete input circuits.</em></figcaption></figure><!-- /wp:embed -->

<!-- wp:heading --><h2 class="wp-block-heading">Digital Inputs And Outputs Are The Basic Robot Interface</h2><!-- /wp:heading -->
<!-- wp:paragraph --><p>A robot <strong>digital input (DI)</strong> may receive a part-present signal, gripper-closed confirmation, conveyor-ready state, or permissive from the PLC. A <strong>digital output (DO)</strong> may command a <a href="https://bitcoinversus.tech/2026/10/02/osetc-022-solenoids-solenoid-valves-basics/"><strong>solenoid valve</strong></a>, turn on a stack light, tell the PLC that the robot is busy, or request another machine to start. When troubleshooting, never assume the software name matches the physical wire: confirm the I/O address, terminal, voltage state, and controller monitor screen. The same principle applies to <a href="https://bitcoinversus.tech/2026/10/02/osetc-020-limit-switches-proximity-sensors-basics/"><strong>limit switches and proximity sensors</strong></a> and <a href="https://bitcoinversus.tech/2026/10/02/osetc-021-photoelectric-sensors-basics/"><strong>photoelectric sensors</strong></a>: verify the field device and the controller state separately.</p><!-- /wp:paragraph -->


<!-- wp:heading --><h2 class="wp-block-heading">A Handshake Prevents Two Machines From Guessing</h2><!-- /wp:heading -->
<!-- wp:paragraph --><p>A <strong>handshake</strong> is a defined sequence of signals that lets the robot and PLC confirm each step before continuing. A common pattern is <strong>PLC_READY → ROBOT_READY → CYCLE_START → ROBOT_BUSY → CYCLE_COMPLETE</strong>. Fault and reset signals are usually separate. The exact signal names vary by manufacturer, but the logic is the same: neither controller should rely on an unexplained time delay when a positive status signal can prove that the previous step actually happened. This is the same control philosophy used by <a href="https://bitcoinversus.tech/2026/10/01/osetc-018-interlocks-permissives-basics/"><strong>interlocks and permissives</strong></a>.</p><!-- /wp:paragraph -->
<!-- wp:embed {"url":"https://www.youtube.com/watch?v=2naKm2oLt2s","type":"video","providerNameSlug":"youtube","responsive":true,"className":"wp-embed-aspect-16-9 wp-has-aspect-ratio"} --><figure class="wp-block-embed is-type-video is-provider-youtube wp-block-embed-youtube wp-embed-aspect-16-9 wp-has-aspect-ratio"><div class="wp-block-embed__wrapper">
https://www.youtube.com/watch?v=2naKm2oLt2s
</div><figcaption class="wp-element-caption"><em>Cross Company — How to Coordinate Two Universal Robots via I/O. A practical controller-to-controller signaling example.</em></figcaption></figure><!-- /wp:embed -->

<!-- wp:heading --><h2 class="wp-block-heading">End Effectors Need Command And Feedback Signals</h2><!-- /wp:heading -->
<!-- wp:paragraph --><p>A <a href="https://bitcoinversus.tech/2026/10/06/osrtc-004-end-effectors-tool-center-point-setup-grippers-tcp-calibration-payload-io-safe-verification/"><strong>robot gripper</strong></a> requires a command and an independently evaluated feedback signal. A technician may command <strong>DO_GRIP_CLOSE = ON</strong>, then wait for <strong>DI_GRIP_CLOSED = ON</strong> or <strong>DI_PART_PRESENT = ON</strong> before allowing the robot to retract. If the output changes but the input never follows, split the fault into stages: controller output, wiring, valve or electric actuator, mechanical grip, and feedback sensor. That prevents unnecessary reteaching of robot positions when the real problem is electrical or pneumatic.</p><!-- /wp:paragraph -->


<!-- wp:heading --><h2 class="wp-block-heading">Safety Signals Are Not Ordinary Production I/O</h2><!-- /wp:heading -->
<!-- wp:paragraph --><p><a href="https://bitcoinversus.tech/2026/10/04/osrtc-001-industrial-robot-safety-e-stops-safeguarding-safe-workcell-entry/"><strong>Robot safety</strong></a> uses dedicated safety-rated circuits and functions for emergency stops, guard doors, enabling devices, safe speed, and other protective states. A normal PLC bit that says “door closed” is not automatically equivalent to a safety-rated guard interlock. Technicians must know which signals are standard production I/O and which are safety I/O, follow the approved workcell safety design, and never bypass a protective device just to make the cycle run. If a gate opens, the safety system should force the robot into the defined safe condition before ordinary production logic can resume.</p><!-- /wp:paragraph -->


<!-- wp:heading --><h2 class="wp-block-heading">Troubleshoot The Signal Path In One Direction At A Time</h2><!-- /wp:heading -->
<!-- wp:paragraph --><p>When a robot will not start, trace the signal path instead of changing several things at once. Begin at the device that should create the signal, check power and wiring, confirm the PLC or robot input changes, verify the logic condition, then follow the resulting output to the next device. Use the <a href="https://bitcoinversus.tech/2026/10/04/osrtc-002-teach-pendant-jogging-coordinate-frames-speed-safe-manual-positioning/"><strong>teach pendant</strong></a> I/O monitor where supported, and compare it with the PLC I/O table or controller diagnostics. If the robot moves correctly in manual mode but refuses automatic operation, look for missing ready, remote, cycle-start, safety, or fault-reset conditions before suspecting <a href="https://bitcoinversus.tech/2026/10/05/osrtc-003-robot-mastering-calibration-zero-position-encoders-reference-marks-recovery/"><strong>mastering or calibration</strong></a>.</p><!-- /wp:paragraph -->
<!-- wp:embed {"url":"https://www.youtube.com/watch?v=rYv9wCbw5NQ","type":"video","providerNameSlug":"youtube","responsive":true,"className":"wp-embed-aspect-16-9 wp-has-aspect-ratio"} --><figure class="wp-block-embed is-type-video is-provider-youtube wp-block-embed-youtube wp-embed-aspect-16-9 wp-has-aspect-ratio"><div class="wp-block-embed__wrapper">
https://www.youtube.com/watch?v=rYv9wCbw5NQ
</div><figcaption class="wp-element-caption"><em>RealPars — How to Test PLC Digital Inputs and Outputs (Step-by-Step Guide). Input and output fault isolation.</em></figcaption></figure><!-- /wp:embed -->

<!-- wp:heading --><h2 class="wp-block-heading">Worked Example: Basic Robot–PLC Cycle Handshake</h2><!-- /wp:heading -->
<!-- wp:list --><ul class="wp-block-list"><li><strong>1.</strong> PLC sets <code>PLC_READY = 1</code> after conveyor and fixture checks pass.</li><li><strong>2.</strong> Robot confirms no fault and sets <code>ROBOT_READY = 1</code>.</li><li><strong>3.</strong> PLC sends a one-cycle or edge-detected <code>CYCLE_START</code>.</li><li><strong>4.</strong> Robot clears <code>ROBOT_READY</code>, sets <code>ROBOT_BUSY = 1</code>, and starts motion.</li><li><strong>5.</strong> Robot commands the gripper output and waits for part-present feedback.</li><li><strong>6.</strong> Robot completes the move, clears <code>ROBOT_BUSY</code>, and sets <code>CYCLE_COMPLETE = 1</code>.</li><li><strong>7.</strong> PLC acknowledges completion and removes the start request before the next cycle.</li><li><strong>8.</strong> Any fault interrupts the sequence and requires the defined fault-clear and reset handshake.</li></ul><!-- /wp:list -->

<!-- wp:heading --><h2 class="wp-block-heading">Technician Troubleshooting Checklist</h2><!-- /wp:heading -->
<!-- wp:list {"ordered":true} --><ol class="wp-block-list"><li>Confirm the workcell is in the correct operating mode and the <a href="https://bitcoinversus.tech/2026/10/04/osrtc-001-industrial-robot-safety-e-stops-safeguarding-safe-workcell-entry/">safety chain</a> is satisfied.</li><li>Check controller and PLC power plus 24 VDC field power where applicable.</li><li>Identify the exact input or output that should change next.</li><li>Verify the physical sensor or actuator state.</li><li>Verify the terminal and wiring state.</li><li>Verify the robot or PLC I/O monitor changes.</li><li>Check the logic condition that consumes that signal.</li><li>Check the corresponding output or handshake response.</li><li>Confirm gripper, fixture, conveyor, or valve feedback before permitting motion.</li><li>After repair, dry-run at reduced speed and verify the entire handshake sequence.</li></ol><!-- /wp:list -->

<!-- wp:heading --><h2 class="wp-block-heading">Electrical Compatibility And Feedback Timeouts</h2><!-- /wp:heading --><!-- wp:paragraph --><p>Digital wiring must match the controller input circuit, signal voltage, reference potential, and output current rating. <a href="https://www.se.com/us/en/faqs/FA101128/">Schneider Electric distinguishes PNP sourcing outputs from NPN sinking outputs</a>. A PNP output supplies current to a compatible sinking input; an NPN output draws current from a compatible sourcing input. The terminal drawing for the exact module remains authoritative. Wiring changes require isolation and verification under the approved maintenance procedure. Protective earth and a signal return must not be treated as interchangeable conductors.</p><!-- /wp:paragraph --><!-- wp:paragraph --><p>The <a href="https://www.universal-robots.com/articles/ur/interface-communication/connecting-internal-inputs-and-outputs-io-on-the-robots-controller/">Universal Robots controller I/O guide</a> distinguishes dedicated general-purpose digital I/O from configurable channels and describes external field-power options. Channel configuration, power limits, and output behavior must be confirmed for the installed controller. Standard process feedback must never replace a required safety function.</p><!-- /wp:paragraph --><!-- wp:paragraph --><p>Every wait for a commanded response requires a defined deadline and recovery path. For example, a hypothetical gripper may require closed-position feedback within 1.5 seconds after its close command. This is an illustrative timeout, not a vendor specification. On expiry, the sequence latches a process fault and prevents the next step. The actual command state during a fault must follow the validated design: removing power from a gripper may release a suspended part. Fault reset must not automatically initiate motion.</p><!-- /wp:paragraph --><!-- wp:heading --><h2 class="wp-block-heading">Runnable Offline Handshake Example</h2><!-- /wp:heading --><!-- wp:paragraph --><p>The following Python simulation exercises handshake logic without connecting to a PLC or robot. READY, BUSY, COMPLETE, and FAULT describe process states only. This example is not a safety controller or a production motion program.</p><!-- /wp:paragraph --><!-- wp:code --><pre class="wp-block-code"><code>def handshake(events, timeout=1.5):
    state = "READY"
    started = None
    acknowledged = False
    for now, request, feedback in events:
        if state == "READY" and request:
            state, started = "BUSY", now
        elif state == "BUSY":
            if now - started &gt;= timeout:
                state = "FAULT"
            elif feedback:
                state = "COMPLETE"
        elif state == "COMPLETE" and not request:
            acknowledged = True
            state = "READY"
        print(now, state)
    return state, acknowledged

assert handshake([(0, True, False), (.4, True, True),
                  (.5, False, False)]) == ("READY", True)
assert handshake([(0, True, False), (1.6, True, False)]) == ("FAULT", False)
</code></pre><!-- /wp:code --><!-- wp:paragraph --><p>Save the program as handshake_demo.py and run <code>python3 handshake_demo.py</code>. The first test prints BUSY, COMPLETE, then READY. The second test prints BUSY, then FAULT. Completion remains latched until the request falls; an unacknowledged COMPLETE state cannot accept a new cycle. The timeout has priority over feedback arriving at or after the deadline. Production implementations additionally require documented startup behavior, stale-feedback detection, reset handling, task timing, and integration tests.</p><!-- /wp:paragraph --><!-- wp:heading --><h2 class="wp-block-heading">Exercises</h2><!-- /wp:heading -->
<!-- wp:list {"ordered":true} --><ol class="wp-block-list"><li>Write a five-signal robot/PLC handshake using READY, START, BUSY, COMPLETE, and FAULT.</li><li>Explain why a fixed two-second delay is weaker than waiting for a verified gripper-closed input.</li><li>A robot DO turns on but the pneumatic gripper does not move. List the fault-isolation steps in order.</li><li>A part-present sensor LED turns on, but the robot DI remains off. Name three likely causes.</li><li>Explain the difference between production I/O and safety-rated I/O.</li><li>Describe how you would separate a missing PLC permissive from a robot mastering problem.</li></ol><!-- /wp:list -->

<!-- wp:heading --><h2 class="wp-block-heading">Knowledge Check + Answers</h2><!-- /wp:heading -->
<!-- wp:list {"ordered":true} --><ol class="wp-block-list"><li><strong>What is a digital input?</strong> A discrete controller signal that reports an external on/off condition.</li><li><strong>What is a digital output?</strong> A discrete controller signal used to command or report an on/off state.</li><li><strong>What is a handshake?</strong> A defined exchange of signals that lets two controllers confirm each step of a sequence.</li><li><strong>Why use feedback instead of only a delay?</strong> Feedback reports the monitored condition; sensor placement and diagnostics determine whether it reliably confirms the required physical action.</li><li><strong>What should be checked when an output is on but the actuator does not move?</strong> Wiring, field power, valve or drive, actuator mechanics, and utility supply.</li><li><strong>Is ordinary PLC I/O automatically safety-rated?</strong> No. Safety functions require the approved safety-rated architecture and devices.</li><li><strong>What should a technician trace first when an automatic cycle will not start?</strong> The first missing permissive or handshake signal in the sequence.</li></ol><!-- /wp:list -->

<!-- wp:heading --><h2 class="wp-block-heading">Conclusion</h2><!-- /wp:heading -->
<!-- wp:paragraph --><p>A robot workcell becomes reliable when every machine proves its state instead of guessing. The <strong>PLC</strong> coordinates the cell, the robot exchanges ready/busy/complete states, <a href="https://bitcoinversus.tech/2026/10/02/osetc-020-limit-switches-proximity-sensors-basics/"><strong>sensors</strong></a> prove what physically happened, and <a href="https://bitcoinversus.tech/2026/10/06/osrtc-004-end-effectors-tool-center-point-setup-grippers-tcp-calibration-payload-io-safe-verification/"><strong>end-effectors</strong></a> use command-and-feedback pairs to confirm successful work. The technician’s job is to trace those signals in order, keep production logic separate from safety logic, and repair the real failed link rather than reteaching robot motion unnecessarily. That signal-by-signal discipline is what turns the manual motion skills from OSRTC.002 and the tool setup skills from OSRTC.004 into a complete automated workcell.</p><!-- /wp:paragraph -->


<!-- wp:heading --><h2 class="wp-block-heading">Prior Lessons And References</h2><!-- /wp:heading -->
<!-- wp:list --><ul class="wp-block-list"><li><a href="https://bitcoinversus.tech/2026/10/04/osrtc-001-industrial-robot-safety-e-stops-safeguarding-safe-workcell-entry/">OSRTC.001 — Industrial Robot Safety</a></li><li><a href="https://bitcoinversus.tech/2026/10/04/osrtc-002-teach-pendant-jogging-coordinate-frames-speed-safe-manual-positioning/">OSRTC.002 — Teach Pendant Basics</a></li><li><a href="https://bitcoinversus.tech/2026/10/05/osrtc-003-robot-mastering-calibration-zero-position-encoders-reference-marks-recovery/">OSRTC.003 — Robot Mastering and Calibration</a></li><li><a href="https://bitcoinversus.tech/2026/10/06/osrtc-004-end-effectors-tool-center-point-setup-grippers-tcp-calibration-payload-io-safe-verification/">OSRTC.004 — End Effectors and TCP Setup</a></li><li><a href="https://bitcoinversus.tech/2026/10/01/osetc-018-interlocks-permissives-basics/">OSETC.018 — Interlocks and Permissives</a></li></ul><!-- /wp:list -->

<!-- wp:heading {"level":3} --><h3 class="wp-block-heading">BitcoinVersus.Tech</h3><!-- /wp:heading -->

<!-- wp:paragraph --><p><strong><em>Editor’s Note:</em></strong> Robot and PLC I/O names, voltage levels, safety architectures, remote-start methods, and handshake conventions vary by manufacturer and facility. Follow the approved electrical drawings, robot manual, PLC program documentation, and workcell safety procedure for the equipment being serviced.</p><!-- /wp:paragraph -->
<!-- wp:paragraph --><p><strong><em>We volunteer daily to help ensure the credibility of the information on this platform is Verifiably True. If you would like to support our research initiatives, please donate here: 3C9o19EH5HSiwEPyCTmEKzxhNCbo2X6TTb</em></strong></p><!-- /wp:paragraph -->
<!-- wp:paragraph --><p>BitcoinVersus.tech is not a financial advisor. Content is provided for informational purposes.</p><!-- /wp:paragraph -->